### ISSUE TITLE
Single page app

### ISSUE THREAD

**Issue by Maxtermax** [H4ckdo/Quibdojs#1]
# Single page app

For this app  gonna be single page application for make more fast at load work, for that is better use backbone.js o angular.js at frontend, we can move for that ?

**Comment by xfry** [comment]
The idea behind this site is give the possibilities to another members of the community to contribute and learn from the site. This is the approach of Progressive enhancement to allow beginners members understand whats how the code work with Nodejs and Express and then go forward turning the site on a Single Page Application.

Keeping it simple is the right way.

**Comment by Maxtermax** [comment]
ok
